version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  run:
    desc: Run proxy server (uses run script)
    cmds:
      - cmd: cmd /c "{{.TASKFILE_DIR}}\\run.bat"
        platforms: [windows]
      - cmd: bash ./run.sh
        platforms: [linux, darwin]

  run:reload:
    desc: Run proxy server with autoreload
    cmds:
      - cmd: cmd /c call "{{.TASKFILE_DIR}}\\run.bat" --reload
        platforms: [windows]
      - cmd: bash ./run.sh --reload
        platforms: [linux, darwin]

  forwarder:
    desc: Run TCP forwarder (separate venv)
    cmds:
      - cmd: cmd /c "{{.TASKFILE_DIR}}\\run_forwarder.bat"
        platforms: [windows]
      - cmd: bash ./run_forwarder.sh
        platforms: [linux, darwin]

  install:
    desc: Create venv + sync dependencies (uses install script)
    cmds:
      - cmd: cmd /c "{{.TASKFILE_DIR}}\\install.bat"
        platforms: [windows]
      - cmd: bash ./install.sh
        platforms: [linux, darwin]

  install:dev:
    desc: Sync dev dependencies into the project venv
    cmds:
      - uv sync --extra dev

  test:
    desc: Run tests
    cmds:
      - uv run pytest tests -v

  clean:
    desc: Clear all logs (deletes all files in logs directory except database)
    cmds:
      - cmd: cmd /c if exist "{{.TASKFILE_DIR}}\logs\yaLLM.db" move "{{.TASKFILE_DIR}}\logs\yaLLM.db" "{{.TASKFILE_DIR}}\logs\yaLLM.db.bak" && rmdir /s /q "{{.TASKFILE_DIR}}\logs" && mkdir "{{.TASKFILE_DIR}}\logs" && if exist "{{.TASKFILE_DIR}}\logs\yaLLM.db.bak" move "{{.TASKFILE_DIR}}\logs\yaLLM.db.bak" "{{.TASKFILE_DIR}}\logs\yaLLM.db"
        platforms: [windows]
      - cmd: bash -c 'if [ -f "{{.TASKFILE_DIR}}/logs/yaLLM.db" ]; then mv "{{.TASKFILE_DIR}}/logs/yaLLM.db" "{{.TASKFILE_DIR}}/logs/yaLLM.db.bak"; fi && rm -rf "{{.TASKFILE_DIR}}/logs" && mkdir -p "{{.TASKFILE_DIR}}/logs" && if [ -f "{{.TASKFILE_DIR}}/logs/yaLLM.db.bak" ]; then mv "{{.TASKFILE_DIR}}/logs/yaLLM.db.bak" "{{.TASKFILE_DIR}}/logs/yaLLM.db"; fi'
        platforms: [linux, darwin]

  db:migrate:
    desc: Run database migrations
    cmds:
      - uv run alembic upgrade head

  db:rollback:
    desc: Rollback last database migration
    cmds:
      - uv run alembic downgrade -1

  db:revision:
    desc: Create new migration (provide message as argument)
    cmds:
      - uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  db:current:
    desc: Show current database revision
    cmds:
      - uv run alembic current

  db:history:
    desc: Show migration history
    cmds:
      - uv run alembic history

  db:upgrade:
    desc: Upgrade database to latest revision
    cmds:
      - uv run alembic upgrade head

  db:heads:
    desc: Show current heads
    cmds:
      - uv run alembic heads
