version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  run:
    desc: Run proxy server (uses run script)
    cmds:
      - cmd: cmd /c "{{.TASKFILE_DIR}}\\run.bat"
        platforms: [windows]
      - cmd: bash ./run.sh
        platforms: [linux, darwin]

  run:reload:
    desc: Run proxy server with autoreload
    cmds:
      - cmd: cmd /c call "{{.TASKFILE_DIR}}\\run.bat" --reload
        platforms: [windows]
      - cmd: bash ./run.sh --reload
        platforms: [linux, darwin]

  forwarder:
    desc: Run TCP forwarder (separate venv)
    cmds:
      - cmd: cmd /c "{{.TASKFILE_DIR}}\\run_forwarder.bat"
        platforms: [windows]
      - cmd: bash ./run_forwarder.sh
        platforms: [linux, darwin]

  install:
    desc: Create venv + sync dependencies (uses install script)
    cmds:
      - cmd: cmd /c "{{.TASKFILE_DIR}}\\install.bat"
        platforms: [windows]
      - cmd: bash ./install.sh
        platforms: [linux, darwin]

  install:dev:
    desc: Sync dev dependencies into the project venv
    cmds:
      - uv sync --extra dev

  test:
    desc: Run tests
    cmds:
      - uv run pytest tests -v
